---
name: "Multiple Imputations (mice) Intermediate"
author: "HIV Estimates Accuracy tool"
title: "Multiple Imputations (mice)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_fragment:
    number_sections: no
    smart: yes
    fig_caption: yes
params:
  InputData: NA    
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, results = "markup", include = TRUE, fig.height = 10, fig.width = 10, warning = FALSE, message = FALSE)
require(shiny)
```

```{r, results='asis'}
cat(sprintf("# %d. Multiple Imputations (mice)\n", params$InputData$RunIdx))
```

```{r, results='asis'}
femaleAllXCols <- params$InputData$Artifacts$F$X_COLS$All
femaleKeptXCols <- params$InputData$Artifacts$F$X_COLS$Kept
maleAllXCols <- params$InputData$Artifacts$M$X_COLS$All
maleKeptXCols <- params$InputData$Artifacts$M$X_COLS$Kept
 
femaleRemovedXCols <- setdiff(femaleAllXCols, femaleKeptXCols)
maleRemovedXCols <- setdiff(maleAllXCols, maleKeptXCols)

femaleAllYCols <- params$InputData$Artifacts$F$Y_COLS$All
femaleKeptYCols <- params$InputData$Artifacts$F$Y_COLS$Kept
maleAllYCols <- params$InputData$Artifacts$M$Y_COLS$All
maleKeptYCols <- params$InputData$Artifacts$M$Y_COLS$Kept
 
femaleRemovedYCols <- setdiff(femaleAllYCols, femaleKeptYCols)
maleRemovedYCols <- setdiff(maleAllYCols, maleKeptYCols)

if (length(femaleRemovedXCols) > 0 | length(femaleRemovedYCols) > 0 | 
    length(maleRemovedXCols) > 0 | length(maleRemovedYCols) > 0) {
  cat("<p>Some attributes in the input data have not been processed with this adjustment due to insufficient data:</p>",
      "<ul>")
  if (length(femaleRemovedXCols) > 0 | length(femaleRemovedYCols) > 0) {
    cat("<li>Female gender<ul>")
    if (length(femaleRemovedXCols) > 0) {
      cat("<li>Covariates: ", femaleRemovedXCols, "</li>")
    }
    if (length(femaleRemovedYCols) > 0) {
      cat("<li>Outputs: ", femaleRemovedYCols, "</li>")
    }
    cat("</ul></li>")
  }
  if (length(maleRemovedXCols) > 0 | length(maleRemovedYCols) > 0) {
    cat("<li>Male gender<ul>")
    if (length(maleRemovedXCols) > 0) {
      cat("<li>Covariates: ", maleRemovedXCols, "</li>")
    }
    if (length(maleRemovedYCols) > 0) {
      cat("<li>Outputs: ", maleRemovedYCols, "</li>")
    }
    cat("</ul></li>")
  }
  cat("</ul>")
}
```

<!--html_preserve-->
<div class="tabbable">
<!--/html_preserve-->
```{r, results='asis', echo = FALSE}
genders <- names(params$InputData$Artifacts)
genderNameMapping <- c("F" = "Female", "M" = "Male", "O" = "Other")
tabsHeader <- c()
for (genderIdx in seq_along(genders)) {
  gender <- genders[genderIdx]
  genderName <- genderNameMapping[gender]
  class <- ifelse(genderIdx == 1, " class='active'", "")
  tabsHeader[gender] <- sprintf(
    "<li%s><a href='#miceTab%s' data-toggle='tab' data-value='miceVal%s'>%s</a></li>",
    class, gender, gender, genderName
  )
}
tabsHeader <- paste(tabsHeader, collapse = "")
cat(knitr::knit_expand(text = "<ul class='nav nav-tabs'>{{tabsHeader}}</ul>"))

cat(sprintf("<div class='tab-content'>"))
for (genderIdx in seq_along(genders)) {
  gender <- genders[genderIdx]
  genderName <- genderNameMapping[gender]
  class <- ifelse(genderIdx == 1, " active", "")
  content <- GetMiceDiagnosticPlot(params$InputData$Artifacts[[gender]]$Mids)
  cat(
    sprintf("<div class='tab-pane%s' id='miceTab%s' data-value='miceVal%s'>", class, gender, gender)
  )
  knitr::normal_print(content)
  cat(sprintf("</div>"))
}
cat(sprintf("</div>"))
```
<!--html_preserve-->
<div>
<!--/html_preserve-->


<!-- <!--html_preserve--> -->
<!-- <div class="tabbable"> -->
<!--   <ul class="nav nav-tabs"> -->
<!--     <li class="active"> -->
<!--       <a href="#miceTabDiagFemale" data-toggle="tab" data-value="Female">Female</a> -->
<!--     </li> -->
<!--     <li> -->
<!--       <a href="#miceTabDiagMale" data-toggle="tab" data-value="Male">Male</a> -->
<!--     </li> -->
<!--   </ul> -->
<!--   <div class="tab-content"> -->
<!--     <div class="tab-pane active" data-value="Female" id="miceTabDiagFemale"> -->
<!-- <!--/html_preserve--> -->

<!-- <!-- ## Diagnostic plots for Gender = \"Female\" --> -->

<!-- Maximum 5 first chains (imputations) are displayed. -->

<!-- **Figure 1. Imputed values per sample**<br /> -->
<!-- ```{r} -->
<!-- print(GetMiceDiagnosticPlot(params$InputData$Artifacts$F$Mids)) -->
<!-- ``` -->

<!-- **Figure 2. Distributions of imputed values**<br /> -->
<!-- ```{r, fig.height = 3} -->
<!-- colNames <- params$InputData$Artifacts$F$Y_COLS$Kept -->
<!-- dtF <- params$InputData$Table[Gender == "F"] -->
<!-- for (colName in colNames) { -->
<!--   PlotMultipleCharts( -->
<!--     list( -->
<!--       GetImputedDistPlots(colName = colName, dt = dtF, missingOnly = TRUE), -->
<!--       GetImputedDistPlots(colName = colName, dt = dtF, missingOnly = FALSE) -->
<!--     ), -->
<!--     cols = 2 -->
<!--   ) -->
<!-- } -->
<!-- ``` -->

<!-- <!--html_preserve--> -->
<!--     </div> -->
<!--     <div class="tab-pane" data-value="Male" id="miceTabDiagMale"> -->
<!-- <!--/html_preserve--> -->

<!-- <!-- ## Diagnostic plots for Gender = \"Male\" --> -->

<!-- Maximum 5 first chains (imputations) are displayed. -->

<!-- **Figure 3. Imputed values plot per sample**<br /> -->
<!-- ```{r} -->
<!-- print(GetMiceDiagnosticPlot(params$InputData$Artifacts$M$Mids)) -->
<!-- ``` -->

<!-- **Figure 4. Distributions of imputed values**<br /> -->
<!-- ```{r, fig.height = 3} -->
<!-- colNames <- params$InputData$Artifacts$M$Y_COLS$Kept -->
<!-- dtM <- params$InputData$Table[Gender == "M"] -->
<!-- for (colName in colNames) { -->
<!--   PlotMultipleCharts( -->
<!--     list( -->
<!--       GetImputedDistPlots(colName = colName, dt = dtM, missingOnly = TRUE), -->
<!--       GetImputedDistPlots(colName = colName, dt = dtM, missingOnly = FALSE) -->
<!--     ), -->
<!--     cols = 2 -->
<!--   ) -->
<!-- } -->
<!-- ``` -->

<!-- <!--html_preserve--> -->
<!--     </div> -->
<!--   </div> -->
<!-- </div> -->
<!-- <!--/html_preserve--> -->
