---
name: "Multiple Imputations (jomo) Intermediate"
author: "HIV Estimates Accuracy tool"
title: "Multiple Imputations (jomo)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_fragment:
    number_sections: no
    smart: yes
    fig_caption: yes
params:
  InputData: NA
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, results = "asis", include = TRUE, fig.height = 10, fig.width = 12, warning = FALSE, message = FALSE)
```

```{r, results='asis'}
cat(sprintf("# %d. Multiple Imputations (jomo)", params$InputData$RunIdx))
```

```{r, results='asis'}
femaleAllXCols <- params$InputData$Artifacts$F$X_COLS$All
femaleKeptXCols <- params$InputData$Artifacts$F$X_COLS$Kept
maleAllXCols <- params$InputData$Artifacts$M$X_COLS$All
maleKeptXCols <- params$InputData$Artifacts$M$X_COLS$Kept
 
femaleRemovedXCols <- setdiff(femaleAllXCols, femaleKeptXCols)
maleRemovedXCols <- setdiff(maleAllXCols, maleKeptXCols)

femaleAllYCols <- params$InputData$Artifacts$F$Y_COLS$All
femaleKeptYCols <- params$InputData$Artifacts$F$Y_COLS$Kept
maleAllYCols <- params$InputData$Artifacts$M$Y_COLS$All
maleKeptYCols <- params$InputData$Artifacts$M$Y_COLS$Kept
 
femaleRemovedYCols <- setdiff(femaleAllYCols, femaleKeptYCols)
maleRemovedYCols <- setdiff(maleAllYCols, maleKeptYCols)

if (length(femaleRemovedXCols) > 0 | length(femaleRemovedYCols) > 0 | 
    length(maleRemovedXCols) > 0 | length(maleRemovedYCols) > 0) {
  cat("<p>Some attributes in the input data have not been processed with this adjustment due to insufficient data:</p>",
      "<ul>")
  if (length(femaleRemovedXCols) > 0 | length(femaleRemovedYCols) > 0) {
    cat("<li>Female gender<ul>")
    if (length(femaleRemovedXCols) > 0) {
      cat("<li>Covariates: ", femaleRemovedXCols, "</li>")
    }
    if (length(femaleRemovedYCols) > 0) {
      cat("<li>Outputs: ", femaleRemovedYCols, "</li>")
    }
    cat("</ul></li>")
  }
  if (length(maleRemovedXCols) > 0 | length(maleRemovedYCols) > 0) {
    cat("<li>Male gender<ul>")
    if (length(maleRemovedXCols) > 0) {
      cat("<li>Covariates: ", maleRemovedXCols, "</li>")
    }
    if (length(maleRemovedYCols) > 0) {
      cat("<li>Outputs: ", maleRemovedYCols, "</li>")
    }
    cat("</ul></li>")
  }
  cat("</ul>")
}
```

## Diagnostic plots for Gender = \"Female\"

**Figure 1. Trace plot**<br />
```{r}
print(GetMCMCBetasPlot(params$InputData$Artifacts$F$Beta))
```

Legend:<br />
```{r}
colNames <- colnames(params$InputData$Artifacts$F$Beta[, , 1])
categoricalNames <- grep("\\.", colNames, value = TRUE)
continuousNames <- setdiff(colNames, categoricalNames)

rowNames <- row.names(params$InputData$Artifacts$F$Beta[, , 1])
coefNames <- grep("(Intercept|SplineKnot)", rowNames, value = TRUE)
covariateNames <- setdiff(rowNames, coefNames)

cat(sprintf("Continuous outcomes: %s<br />", paste(continuousNames, collapse = ", ")))
cat(sprintf("Categorical outcomes (latent normal variables): %s<br />", paste(categoricalNames, collapse = ", ")))
cat(sprintf("Covariate variables: %s<br />", paste(covariateNames, collapse = ", ")))
cat(sprintf("Cubic spline coefficients and intercept: %s<br />", paste(coefNames, collapse = ", ")))
```

**Figure 2. Autocorrelation plot**<br />
```{r}
print(GetMCMCAutoCorrelationPlot(params$InputData$Artifacts$F$Covariance))
```

Legend:<br />
```{r}
colNames <- colnames(params$InputData$Artifacts$F$Covariance[, , 1])
categoricalNames <- grep("\\.", colNames, value = TRUE)
continuousNames <- setdiff(colNames, categoricalNames)

cat(sprintf("Continuous outcomes: %s<br />", paste(continuousNames, collapse = ", ")))
cat(sprintf("Categorical outcomes (latent normal variables): %s<br />", paste(categoricalNames, collapse = ", ")))
```

**Figure 3. Distributions of imputed values**<br />
```{r, fig.height = 3}
colNames <- params$InputData$Artifacts$F$Y_COLS$Kept
dtF <- params$InputData$Table[Gender == "F"]
for (colName in colNames) {
  PlotMultipleCharts(
    list(
      GetImputedDistPlots(colName = colName, dt = dtF, missingOnly = TRUE),
      GetImputedDistPlots(colName = colName, dt = dtF, missingOnly = FALSE)
    ),
    cols = 2
  )
}
```

## Diagnostic plots for Gender = \"Male\"

**Figure 4. Trace plot**<br />
```{r}
print(GetMCMCBetasPlot(params$InputData$Artifacts$M$Beta))
```

Legend:<br />
```{r}
colNames <- colnames(params$InputData$Artifacts$M$Beta[, , 1])
categoricalNames <- grep("\\.", colNames, value = TRUE)
continuousNames <- setdiff(colNames, categoricalNames)

rowNames <- row.names(params$InputData$Artifacts$M$Beta[, , 1])
coefNames <- grep("(Intercept|SplineKnot)", rowNames, value = TRUE)
covariateNames <- setdiff(rowNames, coefNames)

cat(sprintf("Continuous outcomes: %s<br />", paste(continuousNames, collapse = ", ")))
cat(sprintf("Categorical outcomes (latent normal variables): %s<br />", paste(categoricalNames, collapse = ", ")))
cat(sprintf("Covariate variables: %s<br />", paste(covariateNames, collapse = ", ")))
cat(sprintf("Cubic spline coefficients and intercept: %s<br />", paste(coefNames, collapse = ", ")))
```

**Figure 5. Autocorrelation plot**<br />
```{r}
print(GetMCMCAutoCorrelationPlot(params$InputData$Artifacts$M$Covariance))
```

Legend:<br />
```{r}
colNames <- colnames(params$InputData$Artifacts$M$Covariance[, , 1])
categoricalNames <- grep("\\.", colNames, value = TRUE)
continuousNames <- setdiff(colNames, categoricalNames)

cat(sprintf("Continuous outcomes: %s<br />", paste(continuousNames, collapse = ", ")))
cat(sprintf("Categorical outcomes (latent normal variables): %s<br />", paste(categoricalNames, collapse = ", ")))
```

**Figure 6. Distributions of imputed values**<br />
```{r, fig.height = 3}
colNames <- params$InputData$Artifacts$M$Y_COLS$Kept
dtM <- params$InputData$Table[Gender == "M"]
for (colName in colNames) {
  PlotMultipleCharts(
    list(
      GetImputedDistPlots(colName = colName, dt = dtM, missingOnly = TRUE),
      GetImputedDistPlots(colName = colName, dt = dtM, missingOnly = FALSE)
    ),
    cols = 2
  )
}
```
