---
name: "Multiple Imputations (jomo) Diagnostic"
author: "HIV Estimates Accuracy tool"
title: "Multiple Imputations (jomo)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_fragment:
    number_sections: yes
    smart: yes
    fig_caption: yes
params:
  InputData: NA
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, results = "markup", include = TRUE, fig.height = 10, fig.width = 10)

require(data.table, quietly = TRUE)
require(coda, quietly = TRUE)
```

Output of the convergence checking procedure:
```{r echo = FALSE, warning = FALSE}

data <- copy(params[["InputData"]]$Table)
parameters <- params[["InputData"]]$Parameters

# 1. Measures years from earlier diagnosis year
data[, DY := DateOfDiagnosisYear - min(DateOfDiagnosisYear)]

# 2. Split by gender to data sets
dataSets <- data[Gender != ""]
dataSets <- split(dataSets, by = c("Gender"))

workerFunction <- function(dataSet, nburn, nsdf) {
  # Define covariates
  xColNames <- c("AIDS")
  # Define outcomes
  yColNames <- c("Age", "SqCD4", "Transmission", "Migr")
  
  # Create splines with proper names and intercept
  splineBasisMatrix <- as.data.table(splines::ns(dataSet$DY, df = nsdf))
  setnames(splineBasisMatrix, paste0("V", colnames(splineBasisMatrix)))
  intercept <- 1L
  
  # Define covariates of joint imputation model
  X <- cbind(dataSet[, ..xColNames],
           Intercept = intercept,
           splineBasisMatrix)
  # Define outcomes of joint imputation model
  Y <- dataSet[, ..yColNames]
  
  # Workaround for jomo bug:
  # Not used levels must be removed
  X <- droplevels(X)
  Y <- droplevels(Y)
  
  imp <- jomo::jomo.MCMCchain(Y = Y, X = X, nburn = nburn)
}

if (parameters$runInParallel) {
  # Run in parallel
  cl <- parallel::makeCluster(2)
  parallel::clusterExport(cl, "libPaths")
  parallel::clusterEvalQ(cl, {
    .libPaths(libPaths)
    library(data.table)
  })
  outputData <- parallel::parLapply(cl,
                                    dataSets,
                                    workerFunction,
                                    nburn = parameters$nburn,
                                    nsdf = parameters$nsdf)
  parallel::stopCluster(cl)
} else {
  # Run sequentially
  outputData <- lapply(dataSets,
                       workerFunction,
                       nburn = parameters$nburn,
                       nsdf = parameters$nsdf)
}
```

# Female

**Figure 1. Trace plot**<br />
```{r}
PlotMCMCDiagnostic(outputData[[1]]$collectbeta, plotType = "trace")
```

**Figure 2. Autocorrelation plot**<br />
```{r}
PlotMCMCDiagnostic(outputData[[1]]$collectbeta, plotType = "autocorrelation")
```

# Male

**Figure 3. Trace plot**<br />
```{r}
PlotMCMCDiagnostic(outputData[[2]]$collectbeta, plotType = "trace")
```

**Figure 4. Autocorrelation plot**<br />
```{r}
PlotMCMCDiagnostic(outputData[[2]]$collectbeta, plotType = "autocorrelation")
```
